### ISSUE TITLE
Failed to render #1

### ISSUE THREAD

**Issue by phelipelc** [chenyun122/StepIndicator#10]
refer #1 same error in xib xcode 9.4.1.
![screen shot 2019-02-14 at 10 40 51](https://user-images.githubusercontent.com/25186232/52787453-05d17300-3045-11e9-92f8-4e1de6b46841.png)

**Comment by chenyun122** [comment]
@phelipelc , thanks for using the library. This problem is not the same as the #1 issue. Your problem looks like the code signature is missing, which is required by 'XLPagerTabStrip.framework'. Please check the settings in the project's Targets/General.

**Comment by chenyun122** [comment]
Proper steps for rendering in Storyboard: [Link](https://github.com/chenyun122/StepIndicator/issues/14#issuecomment-496760710)
