### ISSUE TITLE
Storyboard designable build fail

### ISSUE THREAD

**Issue by cskime** [chenyun122/StepIndicator#14]
<img width="1053" alt="스크린샷 2019-04-18 17 43 32" src="https://user-images.githubusercontent.com/42177438/56348507-8a856c80-6201-11e9-92cd-04f3f01926ae.png">

i don't know about designable, so i dont' know what is the problem, and what can i do

**Comment by chenyun122** [comment]
Sometimes Xcode needs time to build designable contents. What we can do is waiting, or close and reopen the storyboard, or remove the View from Storyboard and add it again. Just take a few tries.

**Comment by wasim-dev** [comment]
I think its problem with new Xcode 10.2.1, As i tried all possible ways i.e. cleaning build. Reopen storyboard, restarting Xcode but it seems to be a valid issue. even i tried to add 

post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
  end

and run the pods again but it is still a problem. Is anyone else who is facing the issue?

Language = Swift 5
Xcode: 10.2.1

**Comment by chenyun122** [comment]
The first time, you add a UIView to Storyboard and change the class to StepIndicatorView, the Xcode will build the library, and we wait for this:
![Step1](https://user-images.githubusercontent.com/3788227/58525024-c64a2380-81fc-11e9-9d7a-0b542d98efd6.png)

Once Xcode has done build, we need to set the number of steps ( empty value means an empty view ):
![step22](https://user-images.githubusercontent.com/3788227/58525171-52f4e180-81fd-11e9-8e7c-26e57d46519e.png)

After the number of step set, the StepIndicatorView will be displayed appropriately:
![Step3](https://user-images.githubusercontent.com/3788227/58525026-c6e2ba00-81fc-11e9-909b-ffb0830d2e1a.png)
