### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by fichna** [chenyun122/StepIndicator#15]
Please, change in AnnularLayer
`self.centerTextLayer.alignmentMode = kCAAlignmentCenter`
to 
`self.centerTextLayer.alignmentMode = .center`
and 
`animation.fillMode = kCAFillModeForwards`
to
`animation.fillMode = .forwards`
for Swift 5 support. Sorry, I don't know how to create pull request.

**Comment by chenyun122** [comment]
Thanks for the post. The last version on Github is already Swift 5 supported. Maybe the codes from CocoaPods are an old version, I am sorry that I forgot to update them. Now the Cocoapods version is up to date. Please update it with 1.0.7 version. Thanks.
