### ISSUE TITLE
RTL Support 

### ISSUE THREAD

**Issue by nadagamal** [chenyun122/StepIndicator#2]
Hello,
First, I want to thank you for your library 👍 . 
Second, how can I support RTL direction on your component.

Thank you :)
Nada Gamal

**Comment by chenyun122** [comment]
Thanks for using. I need to improve it to support RTL direction, please give me some time.

**Comment by chenyun122** [comment]
Hi @nadagamal , RTL is supported now with new 1.0.6 version. Please try it.
